name: mi_futbol_app
description: "Mi Fútbol DANS - App de streaming de fútbol."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # El Sabueso - navegador invisible
  flutter_inappwebview: ^6.1.5

  # Reproductor de video
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5

  # Estado y red
  provider: ^6.1.2
  http: ^1.2.1
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
